# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField()),
                ('subject', models.CharField(max_length=50)),
                ('clas', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=50)),
                ('diff', models.CharField(max_length=20)),
            ],
        ),
    ]
