# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171016_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='que',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='clas',
        ),
        migrations.RemoveField(
            model_name='question',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='Class',
            field=models.CharField(choices=[('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='Question_Image',
            field=models.FileField(default=datetime.datetime(2017, 10, 18, 9, 31, 4, 550741, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='Subject',
            field=models.CharField(choices=[('English', 'English'), ('SocialScience', 'SocialScience'), ('Maths', 'Mathematics'), ('Science', 'Science')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='Topic',
            field=models.CharField(choices=[('patrick', 'patrick'), ('war', 'war'), ('logics', 'logics'), ('gravity', 'gravity')], default=' ', max_length=50),
        ),
    ]
