# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20171018_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Number_of_Questions',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
