# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_question_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Number_of_Questions',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
