# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20171018_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('1', 'WhatWhereAndWhen'), ('2', 'OntheTrailoftheEarliestPeople'), ('3', 'FromGatheringtoGrowingFood'), ('4', 'WhoDidPatrickHomeworkAHouseAHome'), ('5', 'HowtheDogFoundHimselfaNewMaster'), ('6', 'TarosReward')], default=' ', max_length=50),
        ),
    ]
